name: FeatureCI
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Only on DEV branches"
    - name: Run a multi-line script
      run: |
        echo "Only on DEV branches1"
        echo "Only on DEV branches2"